#!/bin/bash

function isIn()
{
if [ -z "$1" ]; then
    return
fi

for i in "${EXPECTED_ARGS[@]}"; do
    if [ "$i" == "$1" ];then
        return 1
    fi
done

return 0
}
EXPECTED_ARGS=( 1 )
E_BADARGS=65

if isIn $# ; then
  echo "Usage: $0 filepath"
  exit $E_BADARGS
fi

FILEPATH=${1%/}
filename="${FILEPATH##*/}"

tar -zcvf "$filename.tar.gz" "$FILEPATH"
